#  Site Configuration

title: Learning Theory Circle
description: >-
  A community of students and researchers who share a passion for the theory of learning

# URL
baseurl: ""
url: "https://learning-theory-circle.github.io"

# Theme
theme: minima
minima:
  skin: classic

# Top Navigation
header_pages:
  - about.md

# Build
plugins:
  - jekyll-feed
show_excerpts: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

collections:
  pages:
    output: true
    permalink: /:name
